name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to staging
        run: |
          # Update the commit hash in the script tag
          sed -i "s/abc123/$GITHUB_SHA/g" index.html
          # Deploy the code to your staging environment
          git push staging master